services:
  - type: web
    name: flask-chatgpt-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Du gibst den Wert im Dashboard ein
