name: Flask App Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-flask:
    runs-on: ubuntu-latest

    steps:
    - name: Quellcode auschecken
      uses: actions/checkout@v3

    - name: Python installieren
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Abhängigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: .env vorbereiten
      run: |
        echo "OPENAI_API_KEY=dummy" > .env

    - name: Flask-App starten & testen
      run: |
        python app.py &
        sleep 5
        curl --fail http://127.0.0.1:5000 || exit 1
